yolov7-gam3 summary: 235 layers, 5134737 parameters, 0 gradients, 12.7 GFLOPs
val: Scanning 'G:\YOLO\yolov5_research-yolov7\mydata\Driver.3\valid\labels' images and labels...250 found, 0 missing, 63 empty, 0 corrupt: 100%|██████████| 250/250 [00:02<00:00, 108.51it/s]
val: WARNING: Cache directory G:\YOLO\yolov5_research-yolov7\mydata\Driver.3\valid is not writeable: [WinError 183] 当文件已存在时，无法创建该文件。: 'G:\\YOLO\\yolov5_research-yolov7\\mydata\\Driver.3\\valid\\labels.cache.npy' -> 'G:\\YOLO\\yolov5_research-yolov7\\mydata\\Driver.3\\valid\\labels.cache'
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 16/16 [00:02<00:00,  5.45it/s]
                 all        250        191      0.752      0.666      0.721      0.292
              Danger        250         34      0.963      0.765      0.884      0.438
               Drink        250         60      0.646        0.9       0.87      0.352
               Phone        250         60      0.788      0.567      0.603      0.147
                Safe        250         37       0.61      0.432      0.528      0.231
Speed: 0.2ms pre-process, 3.8ms inference, 2.6ms NMS per image at shape (16, 3, 640, 640)	151.515
Results saved to runs\val\exp 5 gam3 Aug

200 epochs completed in 1.494 hours.
Optimizer stripped from runs\train\exp\weights\last.pt, 10.6MB
Optimizer stripped from runs\train\exp\weights\best.pt, 10.6MB

Validating runs\train\exp\weights\best.pt...
Fusing layers... 
yolov7-gam3 summary: 235 layers, 5134737 parameters, 0 gradients, 12.7 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 16/16 [00:02<00:00,  5.90it/s]
                 all        250        191      0.754      0.666      0.722      0.292
              Danger        250         34      0.963      0.765      0.884      0.438
               Drink        250         60      0.654        0.9       0.87      0.351
               Phone        250         60      0.789      0.567      0.603      0.147
                Safe        250         37       0.61      0.432      0.532      0.233
Results saved to runs\train\exp

weights: yolov7-tiny.pt
cfg: models/v7_cfg/deploy/yolov7-gam3.yaml
data: mydata\Driver.3\data.yaml
hyp: data\hyps\hyp.scratch-v7.yaml
epochs: 200
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
swin_float: false
aux_ota_loss: false
save_dir: runs\train\exp
