yolov7-gam3 summary: 235 layers, 5134737 parameters, 0 gradients, 12.7 GFLOPs
val: Scanning 'G:\YOLO\yolov5_research-yolov7\mydata\Driver.3\valid\labels' images and labels...250 found, 0 missing, 63 empty, 0 corrupt: 100%|██████████| 250/250 [00:02<00:00, 109.00it/s]
val: WARNING: Cache directory G:\YOLO\yolov5_research-yolov7\mydata\Driver.3\valid is not writeable: [WinError 183] 当文件已存在时，无法创建该文件。: 'G:\\YOLO\\yolov5_research-yolov7\\mydata\\Driver.3\\valid\\labels.cache.npy' -> 'G:\\YOLO\\yolov5_research-yolov7\\mydata\\Driver.3\\valid\\labels.cache'
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 16/16 [00:03<00:00,  5.20it/s]
                 all        250        191      0.788      0.393      0.648      0.331
              Danger        250         34          1          0       0.84      0.555
               Drink        250         60      0.806      0.683      0.772      0.312
               Phone        250         60      0.662      0.458      0.474      0.129
                Safe        250         37      0.684      0.432      0.507      0.329
Speed: 0.2ms pre-process, 4.1ms inference, 3.3ms NMS per image at shape (16, 3, 640, 640)	131.578
Results saved to runs\val\exp 5 gam3 Aug+Mish

172 epochs completed in 5.179 hours.
Optimizer stripped from runs\train\exp\weights\last.pt, 10.6MB
Optimizer stripped from runs\train\exp\weights\best.pt, 10.6MB

Validating runs\train\exp\weights\best.pt...
Fusing layers... 
yolov7-gam3 summary: 235 layers, 5134737 parameters, 0 gradients, 12.7 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 4/4 [00:06<00:00,  1.59s/it]
                 all        250        191      0.788      0.393      0.647      0.329
              Danger        250         34          1          0      0.837      0.551
               Drink        250         60      0.806      0.683      0.771      0.312
               Phone        250         60      0.662      0.458      0.474      0.126
                Safe        250         37      0.686      0.432      0.507      0.328
Results saved to runs\train\exp

weights: yolov7-tiny.pt
cfg: models/v7_cfg/deploy/yolov7-gam3.yaml
data: mydata\Driver.3\data.yaml
hyp: data\hyps\hyp.scratch-v7.yaml
epochs: 200
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
swin_float: false
aux_ota_loss: false
save_dir: runs\train\exp
