yolov7-gam3 summary: 235 layers, 5134737 parameters, 0 gradients, 12.7 GFLOPs
val: Scanning 'G:\YOLO\yolov5_research-yolov7\mydata\Driver.2\valid\labels.cache' images and labels... 250 found, 0 missing, 63 empty, 0 corrupt: 100%|██████████| 250/250 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 16/16 [00:03<00:00,  5.18it/s]
                 all        250        191      0.527      0.602      0.573      0.283
              Danger        250         34      0.831      0.882      0.885      0.597
               Drink        250         60      0.598       0.72      0.686      0.239
               Phone        250         60      0.253        0.4      0.307     0.0867
                Safe        250         37      0.426      0.405      0.414       0.21
Speed: 0.2ms pre-process, 4.4ms inference, 2.7ms NMS per image at shape (16, 3, 640, 640)	136.986
Results saved to runs\val\exp 5 gam3 Mish+Adamw

200 epochs completed in 1.361 hours.
Optimizer stripped from runs\train\exp\weights\last.pt, 10.6MB
Optimizer stripped from runs\train\exp\weights\best.pt, 10.6MB

Validating runs\train\exp\weights\best.pt...
Fusing layers... 
yolov7-gam3 summary: 235 layers, 5134737 parameters, 0 gradients, 12.7 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 8/8 [00:02<00:00,  3.08it/s]
                 all        250        191      0.526      0.603      0.574      0.283
              Danger        250         34      0.828      0.882      0.885        0.6
               Drink        250         60      0.599      0.723      0.685      0.238
               Phone        250         60      0.253        0.4      0.309      0.086
                Safe        250         37      0.423      0.405      0.414       0.21
Results saved to runs\train\exp


weights: yolov7-tiny.pt
cfg: models/v7_cfg/deploy/yolov7-gam3.yaml
data: mydata\Driver.2\data.yaml
hyp: data\hyps\hyp.scratch-v7.yaml
epochs: 200
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: AdamW
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
swin_float: false
aux_ota_loss: false
save_dir: runs\train\exp
