yolov7-gam2 summary: 211 layers, 6123921 parameters, 0 gradients, 14.5 GFLOPs
val: Scanning 'G:\YOLO\yolov5_research-yolov7\mydata\Driver.2\valid\labels.cache' images and labels... 250 found, 0 missing, 63 empty, 0 corrupt: 100%|██████████| 250/250 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 16/16 [00:02<00:00,  5.59it/s]
                 all        250        191      0.626      0.656      0.599      0.335
              Danger        250         34          1      0.873      0.896      0.686
               Drink        250         60      0.843      0.883      0.889      0.376
               Phone        250         60      0.291      0.383      0.372      0.131
                Safe        250         37       0.37      0.486      0.241      0.147
Speed: 0.2ms pre-process, 3.5ms inference, 3.0ms NMS per image at shape (16, 3, 640, 640)	149.253
Results saved to runs\val\exp 5 gam2


进程已结束,退出代码0


weights: yolov7-tiny.pt
cfg: models/v7_cfg/deploy/yolov7-gam2.yaml
data: mydata\Driver.2\data.yaml
hyp: data\hyps\hyp.scratch-v7.yaml
epochs: 200
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
swin_float: false
aux_ota_loss: false
save_dir: runs\train\exp
