yolov7-gam3 summary: 235 layers, 5134737 parameters, 0 gradients, 12.7 GFLOPs
val: Scanning 'G:\YOLO\yolov5_research-yolov7\mydata\Driver.2\valid\labels.cache' images and labels... 250 found, 0 missing, 63 empty, 0 corrupt: 100%|██████████| 250/250 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 16/16 [00:02<00:00,  5.54it/s]
                 all        250        191      0.629      0.674      0.678      0.342
              Danger        250         34      0.964      0.788      0.887        0.6
               Drink        250         60      0.457        0.8      0.783      0.302
               Phone        250         60      0.419      0.493      0.422      0.134
                Safe        250         37      0.675      0.617      0.621      0.333
Speed: 0.2ms pre-process, 3.7ms inference, 2.4ms NMS per image at shape (16, 3, 640, 640)	158.730
Results saved to runs\val\exp 5 gam3

200 epochs completed in 2.721 hours.
Optimizer stripped from runs\train\exp\weights\last.pt, 10.6MB
Optimizer stripped from runs\train\exp\weights\best.pt, 10.6MB

Validating runs\train\exp\weights\best.pt...
Fusing layers... 
yolov7-gam3 summary: 235 layers, 5134737 parameters, 0 gradients, 12.7 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 4/4 [00:03<00:00,  1.00it/s]
                 all        250        191      0.626      0.671      0.679      0.344
              Danger        250         34      0.964      0.786      0.887      0.606
               Drink        250         60      0.456        0.8      0.783      0.304
               Phone        250         60      0.411      0.483      0.422      0.133
                Safe        250         37      0.674      0.616      0.622      0.331
Results saved to runs\train\exp

进程已结束,退出代码0


weights: yolov7-tiny.pt
cfg: models/v7_cfg/deploy/yolov7-gam3.yaml
data: mydata\Driver.2\data.yaml
hyp: data\hyps\hyp.scratch-v7.yaml
epochs: 200
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
swin_float: false
aux_ota_loss: false
save_dir: runs\train\exp
