yolov7 summary: 306 layers, 36496081 parameters, 6194944 gradients, 103.4 GFLOPs
val: Scanning 'G:\YOLO\yolov5_research-yolov7\mydata\Driver.2\valid\labels.cache' images and labels... 250 found, 0 missing, 63 empty, 0 corrupt: 100%|██████████| 250/250 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 16/16 [00:04<00:00,  3.38it/s]
                 all        250        191      0.595      0.473      0.615      0.317
              Danger        250         34          1      0.386      0.861      0.574
               Drink        250         60       0.56        0.9      0.847      0.355
               Phone        250         60      0.298      0.417      0.428       0.16
                Safe        250         37      0.523      0.189      0.325      0.181
Speed: 0.2ms pre-process, 11.6ms inference, 3.3ms NMS per image at shape (16, 3, 640, 640)  66.225
Results saved to runs\val\exp 0


200 epochs completed in 2.290 hours.
Optimizer stripped from runs\train\exp\weights\last.pt, 74.9MB
Optimizer stripped from runs\train\exp\weights\best.pt, 74.9MB

Validating runs\train\exp\weights\best.pt...
Fusing layers... 
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
yolov7 summary: 306 layers, 36496081 parameters, 6194944 gradients, 103.4 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 16/16 [00:03<00:00,  5.26it/s]
                 all        250        191      0.593      0.468      0.612      0.316
              Danger        250         34          1      0.392       0.86      0.573
               Drink        250         60      0.561        0.9      0.846      0.355
               Phone        250         60      0.298      0.417      0.428      0.159
                Safe        250         37      0.511      0.162      0.314      0.176
Results saved to runs\train\exp


weights: yolov7-tiny.pt
cfg: models/v7_cfg/deploy/yolov7.yaml
data: mydata\Driver.2\data.yaml
hyp: data\hyps\hyp.scratch-v7.yaml
epochs: 200
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
swin_float: false
aux_ota_loss: false
save_dir: runs\train\exp
